services:
  nginx-proxy:
    image: jwilder/nginx-proxy    
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html   
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - TRUST_DOWNSTREAM_PROXY=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d:rw
      - ./html:/usr/share/nginx/html:rw
  web:
    build: .
    image: carlosalvro/probandolo:prod
    container_name: django_docker
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=admin.srcocol.com
      - LETSENCRYPT_HOST=admin.srcocol.com
      - LETSENCRYPT_EMAIL=carlose.alvro@gmail.com
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: 
      - "--cleanup"
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
volumes:
  postgres_data:
